added check_not_found function, rearranged some other stuff

diff --git a/tests/settings.sh.in b/tests/settings.sh.in
--- a/tests/settings.sh.in
+++ b/tests/settings.sh.in
@@ -1,7 +1,7 @@
 #!/bin/sh
 # @configure_input@
 #
-# $Id: settings.sh.in,v 1.3 2003/04/24 19:18:17 airborne Exp $
+# $Id: settings.sh.in,v 1.4 2003/04/25 17:56:32 airborne Exp $
 
 # location of the example program used in the tests
 CDDB_QUERY='@abs_top_builddir@/examples/cddb_query -q'
@@ -17,6 +17,20 @@ SUCCESS=0
 FAILURE=1
 SKIPPED=77
 
+# libcddb/cddb_query error codes
+DISC_NOT_FOUND=11
+
+fail()
+{
+    printf 'failed.\n'
+    exit $FAILURE
+}
+
+success()
+{
+    printf 'ok.\n'
+}
+
 check_discid()
 {
     DISCID_STR='CD disc ID is '
@@ -24,10 +38,9 @@ check_discid()
     RET_ID=`sed "/^${DISCID_STR}[0-9a-f]*\$/!d;s/${DISCID_STR}\([0-9a-f]*\)/\1/"`
     printf 'Checking disc ID %s... ' ${EXP_ID}
     if [ ${RET_ID}x != ${EXP_ID}x ]; then
-        printf 'failed.\n'
-        exit $FAILURE
+        fail
     fi
-    printf 'ok.\n'
+    success
 }
 
 diff_res_exp()
@@ -35,10 +48,9 @@ diff_res_exp()
     EXPECTED=$1
     diff - $EXPECTED > /dev/null
     if [ $? -ne 0 ]; then
-        printf 'failed.\n'
-        exit $FAILURE
+        fail
     fi
-    printf 'ok.\n'
+    success
 }
 
 check_read()
@@ -55,4 +67,15 @@ check_query()
     EXP_QUERY="${CDDB_DATA}/${QUERY_HASH}.txt"
     printf 'Checking disc query %s... ' ${QUERY_HASH}
     diff_res_exp $EXP_QUERY
+}
+
+check_not_found()
+{
+    DISC_ID=$1
+    RV=$2
+    printf 'Checking disc not found %s... ' ${DISC_ID}
+    if [ $RV -ne $DISC_NOT_FOUND ]; then
+        fail
+    fi
+    success
 }
