report failures correctly

diff --git a/tests/settings.sh.in b/tests/settings.sh.in
--- a/tests/settings.sh.in
+++ b/tests/settings.sh.in
@@ -1,7 +1,7 @@
 #!/bin/sh
 # @configure_input@
 #
-# $Id: settings.sh.in,v 1.4 2003/04/25 17:56:32 airborne Exp $
+# $Id: settings.sh.in,v 1.5 2003/05/08 19:40:40 airborne Exp $
 
 # location of the example program used in the tests
 CDDB_QUERY='@abs_top_builddir@/examples/cddb_query -q'
@@ -12,6 +12,9 @@ CDDB_CACHE='@abs_srcdir@/testcache'
 # location of test data
 CDDB_DATA='@abs_srcdir@/testdata'
 
+# name of temporary file for result data
+TMP_FILE='./result.tmp'
+
 # test result return codes
 SUCCESS=0
 FAILURE=1
@@ -20,25 +23,71 @@ SKIPPED=77
 # libcddb/cddb_query error codes
 DISC_NOT_FOUND=11
 
+# counters for number of succeeded/failed/skipped/total tests
+CNT_SUCCESS=0
+CNT_FAIL=0
+CNT_SKIP=0
+
 fail()
 {
     printf 'failed.\n'
-    exit $FAILURE
+    CNT_FAIL=`expr $CNT_FAIL + 1`
 }
 
 success()
 {
     printf 'ok.\n'
+    CNT_SUCCESS=`expr $CNT_SUCCESS + 1`
+}
+
+skip()
+{
+    printf 'skipped.\n'
+    CNT_SKIP=`expr $CNT_SKIP + 1`
+}
+
+finalize()
+{
+    CNT_TOTAL=`expr $CNT_SUCCESS + $CNT_FAIL + $CNT_SKIP`
+    echo "Results for $0"
+    if [ $CNT_SUCCESS -gt 0 ]; then
+        echo "  Succeeded: ${CNT_SUCCESS}/${CNT_TOTAL}"
+    fi
+    if [ $CNT_SKIP -gt 0 ]; then
+        echo "  Skipped:   ${CNT_SKIP}/${CNT_TOTAL}"
+    fi
+    if [ $CNT_FAIL -gt 0 ]; then
+        echo "  Failed:    ${CNT_FAIL}/${CNT_TOTAL}"
+    fi
+    if [ $CNT_FAIL -gt 0 ]; then
+        exit $FAILURE
+    elif [ $CNT_SUCCESS -gt 0 -o $CNT_SKIP -eq 0 ]; then
+        exit $SUCCESS
+    else
+        exit $SKIPPED
+    fi
+}
+
+cddb_query()
+{
+    rm $TMP_FILE > /dev/null 2>&1
+    $CDDB_QUERY "$@" > $TMP_FILE
 }
 
 check_discid()
 {
     DISCID_STR='CD disc ID is '
-    EXP_ID=$1
-    RET_ID=`sed "/^${DISCID_STR}[0-9a-f]*\$/!d;s/${DISCID_STR}\([0-9a-f]*\)/\1/"`
-    printf 'Checking disc ID %s... ' ${EXP_ID}
+    RV=$1
+    EXP_ID=$2
+    printf 'Check disc ID %s... ' ${EXP_ID}
+    if [ ${RV} -ne 0 ]; then
+        fail
+        return
+    fi
+    RET_ID=`cat $TMP_FILE | sed "/^${DISCID_STR}[0-9a-f]*\$/!d;s/${DISCID_STR}\([0-9a-f]*\)/\1/"`
     if [ ${RET_ID}x != ${EXP_ID}x ]; then
         fail
+        return
     fi
     success
 }
@@ -46,36 +95,48 @@ check_discid()
 diff_res_exp()
 {
     EXPECTED=$1
-    diff - $EXPECTED > /dev/null
+    diff $TMP_FILE $EXPECTED > /dev/null
     if [ $? -ne 0 ]; then
         fail
+        return
     fi
     success
 }
 
 check_read()
 {
-    DISC_ID=$1
-    EXP_READ="${CDDB_DATA}/${DISC_ID}.txt"
+    RV=$1
+    DISC_ID=$2
     printf 'Checking disc read %s... ' ${DISC_ID}
+    if [ ${RV} -ne 0 ]; then
+        fail
+        return
+    fi
+    EXP_READ="${CDDB_DATA}/${DISC_ID}.txt"
     diff_res_exp $EXP_READ
 }
 
 check_query()
 {
-    QUERY_HASH=$1
-    EXP_QUERY="${CDDB_DATA}/${QUERY_HASH}.txt"
+    RV=$1
+    QUERY_HASH=$2
     printf 'Checking disc query %s... ' ${QUERY_HASH}
+    if [ ${RV} -ne 0 ]; then
+        fail
+        return
+    fi
+    EXP_QUERY="${CDDB_DATA}/${QUERY_HASH}.txt"
     diff_res_exp $EXP_QUERY
 }
 
 check_not_found()
 {
-    DISC_ID=$1
-    RV=$2
+    RV=$1
+    DISC_ID=$2
     printf 'Checking disc not found %s... ' ${DISC_ID}
     if [ $RV -ne $DISC_NOT_FOUND ]; then
         fail
+        return
     fi
     success
 }
